# Generated by Django 4.2.23 on 2025-08-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Unknown Product', max_length=255)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('genuine', 'Genuine'), ('fake', 'Fake'), ('likely_genuine', 'Likely Genuine'), ('likely_fake', 'Likely Fake'), ('possibly_genuine', 'Possibly Genuine'), ('possibly_fake', 'Possibly Fake'), ('uncertain', 'Uncertain')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('model', models.CharField(default='ensemble_svm_rf_distilbert', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='reviewai.review')),
            ],
            options={
                'db_table': 'review_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
