# Generated by Django 4.2.23 on 2025-08-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewai', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.CharField(choices=[('web', 'Web Application'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('shopee', 'Shopee'), ('lazada', 'Lazada'), ('flipkart', 'Flipkart'), ('aliexpress', 'AliExpress'), ('walmart', 'Walmart'), ('alibaba', 'Alibaba'), ('temu', 'Temu'), ('zalora', 'Zalora'), ('carousell', 'Carousell'), ('extension', 'Browser Extension'), ('other', 'Other Platform')], default='web', max_length=20),
        ),
    ]
