# Generated by Django 4.2.23 on 2025-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewai', '0003_review_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
