# Generated by Django 4.2.23 on 2025-09-17 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewai', '0004_review_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('review_create', 'Review Created'), ('review_update', 'Review Updated'), ('review_delete', 'Review Deleted'), ('analysis', 'Review Analyzed'), ('batch_analysis', 'Batch Analysis'), ('user_register', 'User Registered'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
