# Generated by Django 4.2.23 on 2025-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewai', '0007_faq_alter_activitylog_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('process', 'Detection Process'), ('models', 'Models Used'), ('data', 'Data Sources'), ('usage', 'System Usage')], default='general', max_length=50),
        ),
    ]
