# Generated by Django 4.2.23 on 2025-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewai', '0008_remove_faq_created_at_remove_faq_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('process', 'Detection Process'), ('models', 'Models Used'), ('data', 'Data Sources'), ('usage', 'System Usage'), ('nlp', 'NLP'), ('performance', 'Performance'), ('privacy', 'Privacy'), ('features', 'Features'), ('technology', 'Technology'), ('future', 'Future Improvements')], default='general', max_length=50),
        ),
    ]
